### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by GytNGF** [dmosc/gptc#32]
When I run `gptc` with any option like `--help`, I get the following error.

```
bash: /usr/local/bin/gptc: cannot execute binary file: Exec format error
```

I'm running Linux x86_64.

**Comment by dmosc** [comment]
What OS are you trying to install the binary on? The only binary available at the moment is Linux.

- [Error when trying to run Linux on Windows envs](https://stackoverflow.com/a/66971306/11672866).

**Comment by GytNGF** [comment]
Yes I am using Arch Linux x86_64, I don't understand why it is not working... I don't know Rust, but I might try to build it on my computer to test if at least it works this way.

**Comment by dmosc** [comment]
Sg, let me know how it works out. I'll try to look into the issue as well. Let's see if there's a way to compile Rust binaries to multiple architectures.

Also: I compiled the binary on macOS Monterey, I'll try booting up a Linux server and see if it compiles on my end as well.

**Comment by GytNGF** [comment]
Okay, I can confirm it is working on Linux if I build it myself, fixing the build process for multiple architectures should work. Thanks.

**Comment by dmosc** [comment]
I'm on it, and will be releasing the PR shortly.

Thank you so much for the input.

**Comment by dmosc** [comment]
@blkpws, I'm back from the rabbit hole. The only solution I've managed to push the farthest is to natively build `gptc` inside Docker containers with images for each architecture. You can checkout the PR (still pending testing), and hopefully, I can get cross-arch support for the upcoming release.
